### ISSUE TITLE
Code from README does not work

### ISSUE THREAD

**Issue by DataGreed** [schapman1974/tinymongo#60]
Tries running code from "examples" section, got RecursionError

```
from tinymongo import TinyMongoClient
>>> connection = TinyMongoClient()
>>> db = connection.my_tiny_database
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/whatever/my_project/.venv/lib/python3.8/site-packages/tinymongo/tinymongo.py", line 73, in __getattr__
    return TinyMongoDatabase(name, self._foldername, self._storage)
  File "/Users/whatever/my_project/.venv/lib/python3.8/site-packages/tinymongo/tinymongo.py", line 73, in __getattr__
    return TinyMongoDatabase(name, self._foldername, self._storage)
  File "/Users/whatever/my_project/.venv/lib/python3.8/site-packages/tinymongo/tinymongo.py", line 73, in __getattr__
    return TinyMongoDatabase(name, self._foldername, self._storage)
  [Previous line repeated 987 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by MagnetoOptical** [comment]
As of the time of this comment, lines 6-27 of demo.py both provide clues what the recursion issue is all about (not being able to find the base directory for the db) and how to properly initialize the connection so this error can be avoided.

**Comment by schapman1974** [comment]
Current state: resolved in the current code and released in tinymongo 1.1.0. The README quick-start path no longer recurses when accessing connection.my_tiny_database, and this behavior is covered by the current test suite. Closing as fixed.
